Update 5-merge-our-changes.yml

diff --git a/.github/workflows/5-merge-our-changes.yml b/.github/workflows/5-merge-our-changes.yml
--- a/.github/workflows/5-merge-our-changes.yml
+++ b/.github/workflows/5-merge-our-changes.yml
@@ -36,6 +36,12 @@ jobs:
             issue_url=$(gh issue list --repo $REPO --search "in:title Exercise:" --json url,title --jq '.[].url')
           fi
 
+          # Fail if no issue found
+          if [ -z "$issue_url" ]; then
+          echo "No matching issue found. Exiting."
+          exit 1
+          fi
+
           # Save to output
           echo "ISSUE_URL=$issue_url" >> $GITHUB_OUTPUT
         env:
